language: node_js
node_js:
  - "4"
sudo: false
script: "make travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
android:
  components:
  - build-tools-19.1.0               # BuildTools version
  - android-19                       # SDK version
  - sys-img-armeabi-v7a-android-19   # System image